[package]
name = "quic"
version = "0.1.0"
authors = ["Brett Jackson <brett@brettjackson.org>"]
description = "QUIC library for Rust. WIP"
license = "MIT"


[dependencies]
byteorder = "1"
bitfield = "0.0.12"
bitflags = "0.8.2"